export const ITEMS_ACTION_TYPES = {
  FETCH_ITEMS_START: "items/FETCH_ITEMS_START",
  FETCH_ITEMS_SUCCESS: "items/FETCH_ITEMS_SUCCESS",
  FETCH_ITEMS_FAILED: "items/FETCH_ITEMS_FAILED",
};

export default ITEMS_ACTION_TYPES;
